<a href="https://colab.research.google.com/github/Masoud-Ghasemian/BERT/blob/master/Hugging_Face.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
pip install transformers

     |████████████████████████████████| 675kB 2.8MB/s 
     |████████████████████████████████| 1.1MB 13.5MB/s 
     |████████████████████████████████| 890kB 21.2MB/s 
     |████████████████████████████████| 3.8MB 25.0MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=5c474d975a2ca67d1a15b8b46c8f858828e1210fb1d72275b73c1116903068ae
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [ ]:
from transformers import pipeline

In [ ]:
nlp = pipeline('sentiment-analysis')

In [ ]:
nlp('The weather is not perfect')

[{'label': 'NEGATIVE', 'score': 0.9997546672821045}]

In [ ]:
nlp('I am fucking happy')

[{'label': 'POSITIVE', 'score': 0.9998769760131836}]

In [ ]:
nlp('I am happy')

[{'label': 'POSITIVE', 'score': 0.9998801946640015}]

In [ ]:
nlp('I am OK')

[{'label': 'POSITIVE', 'score': 0.9998503923416138}]

In [ ]:
nlp('she is leaving airport')

[{'label': 'NEGATIVE', 'score': 0.9982832670211792}]

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [ ]:
import torch

In [ ]:
tokenizer = AutoTokenizer.from_pretrained('bert-base-cased-finetuned-mrpc')

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained('bert-base-cased-finetuned-mrpc')

In [ ]:
classes = ['not parapharse', 'is parapharase']

In [ ]:
sequence_0 = "The company HuggingFace is based in New York City"
sequence_1 = "Apples are especially bad for your health"
sequence_2 = "HuggingFace's headquarters are situated in Manhattan"

In [ ]:
parapharase = tokenizer.encode_plus(sequence_0,  sequence_2, return_tensors='pt')
not_parapharase = tokenizer.encode_plus(sequence_0,  sequence_1, return_tensors='pt')

In [ ]:
parapharase['input_ids']

tensor([[  101,  1109,  1419, 20164, 10932,  2271,  7954,  1110,  1359,  1107,
          1203,  1365,  1392,   102, 20164, 10932,  2271,  7954,   112,   188,
          3834,  1132,  3629,  1107,  6545,   102]])

In [ ]:
not_parapharase['input_ids']

tensor([[  101,  1109,  1419, 20164, 10932,  2271,  7954,  1110,  1359,  1107,
          1203,  1365,  1392,   102,  7302,  1116,  1132,  2108,  2213,  1111,
          1240,  2332,   102]])

In [ ]:
parapharase_classification_logits = model(**parapharase)[0]
not_parapharase_classification_logits = model(**not_parapharase)[0]

In [ ]:
torch.softmax(parapharase_classification_logits, dim = 1).tolist()[0]

[0.09536287933588028, 0.9046371579170227]

In [ ]:
torch.softmax(not_parapharase_classification_logits, dim = 1)

tensor([[0.9404, 0.0596]], grad_fn=<SoftmaxBackward>)

#Text Generation

In [ ]:
from transformers import pipeline

In [ ]:
text_generator = pipeline('text-generation')

In [ ]:
text_generator('The economy is collapsing', max_length = 100)

Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence


[{'generated_text': 'The economy is collapsing and the world is heading in a different direction. It\'s time to stop believing in a \'good news\' message like a real one-stop shop, with free shipping, safe payments, and secure currency," he said in a statement.\n\nAs you can see from the above images, the money supply of the US with its massive population of immigrants and tourists is falling along with growing job creation in the United States.\n\nMany analysts are predicting an overall unemployment rate of'}]

In [ ]:
summarizer = pipeline('summarization')

In [ ]:
ARTICLE = """ New York (CNN)When Liana Barrientos was 23 years old, she got married in Westchester County, New York.
A year later, she got married again in Westchester County, but to a different man and without divorcing her first husband.
Only 18 days after that marriage, she got hitched yet again. Then, Barrientos declared "I do" five more times, sometimes only within two weeks of each other.
In 2010, she married once more, this time in the Bronx. In an application for a marriage license, she stated it was her "first and only" marriage.
Barrientos, now 39, is facing two criminal counts of "offering a false instrument for filing in the first degree," referring to her false statements on the
2010 marriage license application, according to court documents.
Prosecutors said the marriages were part of an immigration scam.
On Friday, she pleaded not guilty at State Supreme Court in the Bronx, according to her attorney, Christopher Wright, who declined to comment further.
After leaving court, Barrientos was arrested and charged with theft of service and criminal trespass for allegedly sneaking into the New York subway through an emergency exit, said Detective
Annette Markowski, a police spokeswoman. In total, Barrientos has been married 10 times, with nine of her marriages occurring between 1999 and 2002.
All occurred either in Westchester County, Long Island, New Jersey or the Bronx. She is believed to still be married to four men, and at one time, she was married to eight men at once, prosecutors say.
Prosecutors said the immigration scam involved some of her husbands, who filed for permanent residence status shortly after the marriages.
Any divorces happened only after such filings were approved. It was unclear whether any of the men will be prosecuted.
The case was referred to the Bronx District Attorney\'s Office by Immigration and Customs Enforcement and the Department of Homeland Security\'s
Investigation Division. Seven of the men are from so-called "red-flagged" countries, including Egypt, Turkey, Georgia, Pakistan and Mali.
Her eighth husband, Rashid Rajput, was deported in 2006 to his native Pakistan after an investigation by the Joint Terrorism Task Force.
If convicted, Barrientos faces up to four years in prison.  Her next court appearance is scheduled for May 18.
"""

In [ ]:
summarizer(ARTICLE ,  min_length = 5, max_length = 60)

[{'summary_text': 'Liana Barrientos, 39, is charged with two counts of "offering a false instrument for filing in the first degree" In total, she has been married 10 times, with nine of her marriages occurring between 1999 and 2002. She is believed to still be married to four'}]

In [ ]:
from transformers import AutoTokenizer, AutoModelWithLMHead

In [ ]:
tokenizar = AutoTokenizer.from_pretrained('t5-base')

In [ ]:
model = AutoModelWithLMHead.from_pretrained('t5-base')

In [ ]:
inputs = tokenizar.encode("summarize: " + ARTICLE, return_tensors='pt', max_length = 512)

In [ ]:
output = model.generate(inputs, max_length = 150, min_length= 30, early_stopping=True, num_beams = 4, length_penalty=2.0,)

In [ ]:
output[0]

tensor([    0,    16,   792,     6,  1207,  3483,   235,     7,    65,   118,
         4464,   335,   648,     6,    28,  4169,    13,   160,  5281,     7,
        16198,   344,  5247,    11,  4407,     3,     5,   255,    19,  6141,
           12,   341,    36,  4464,    12,   662,  1076,     6,    11,    44,
           80,    97,     6,   255,  4464,  2641,  1076,    44,   728,     3,
            5])

In [ ]:
tokens = tokenizar.convert_ids_to_tokens(output.tolist()[0], skip_special_tokens=True)

In [ ]:
tokenizer.convert_tokens_to_string(tokens)

'▁in ▁total , ▁bar rien to s ▁has ▁been ▁married ▁10 ▁times , ▁with ▁nine ▁of ▁her ▁marriage s ▁occurring ▁between ▁1999 ▁and ▁2002 ▁ . ▁she ▁is ▁believed ▁to ▁still ▁be ▁married ▁to ▁four ▁men , ▁and ▁at ▁one ▁time , ▁she ▁married ▁eight ▁men ▁at ▁once ▁ .'

#Masked Language Model

In [ ]:
nlp_mask = pipeline('fill-mask')

In [ ]:
nlp_mask(f'Ann Arbor is a town in Michigan state with cold winters. Most of people who live in Ann Arbor are {nlp_mask.tokenizer.mask_token} with high salary.')

[{'score': 0.14173559844493866,
  'sequence': '<s> Ann Arbor is a town in Michigan state with cold winters. Most of people who live in Ann Arbor are retirees with high salary.</s>',
  'token': 21156},
 {'score': 0.10389494150876999,
  'sequence': '<s> Ann Arbor is a town in Michigan state with cold winters. Most of people who live in Ann Arbor are employed with high salary.</s>',
  'token': 7460},
 {'score': 0.061790626496076584,
  'sequence': '<s> Ann Arbor is a town in Michigan state with cold winters. Most of people who live in Ann Arbor are unemployed with high salary.</s>',
  'token': 17580},
 {'score': 0.043690312653779984,
  'sequence': '<s> Ann Arbor is a town in Michigan state with cold winters. Most of people who live in Ann Arbor are millionaires with high salary.</s>',
  'token': 36826},
 {'score': 0.038438454270362854,
  'sequence': '<s> Ann Arbor is a town in Michigan state with cold winters. Most of people who live in Ann Arbor are people with high salary.</s>',
  'token

In [ ]:
from transformers import AutoTokenizer, AutoModelWithLMHead


In [ ]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-cased")
model = AutoModelWithLMHead.from_pretrained("distilbert-base-cased")

In [ ]:
sequence = f'Thre are different type of transportation such as ground, {tokenizer.mask_token} and car that cause air pollution '

In [ ]:
inputs=tokenizer.encode(sequence, return_tensors='pt')

In [4]:
import torch
from transformers import BertTokenizer, BertModel, BertForMaskedLM

# OPTIONAL: if you want to have more information on what's happening under the hood, activate the logger as follows
import logging
logging.basicConfig(level=logging.INFO)

# Load pre-trained model tokenizer (vocabulary)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Tokenize input
text = "[CLS] Who was Jim Henson ? [SEP] Jim Henson was a puppeteer [SEP]"
tokenized_text = tokenizer.tokenize(text)

# Mask a token that we will try to predict back with `BertForMaskedLM`
masked_index = 8
tokenized_text[masked_index] = '[MASK]'
assert tokenized_text == ['[CLS]', 'who', 'was', 'jim', 'henson', '?', '[SEP]', 'jim', '[MASK]', 'was', 'a', 'puppet', '##eer', '[SEP]']

# Convert token to vocabulary indices
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
# Define sentence A and B indices associated to 1st and 2nd sentences (see paper)
segments_ids = [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]

# Convert inputs to PyTorch tensors
tokens_tensor = torch.tensor([indexed_tokens])
segments_tensors = torch.tensor([segments_ids])

INFO:filelock:Lock 140709407808368 acquired on /root/.cache/torch/transformers/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084.lock
INFO:transformers.file_utils:https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt not found in cache or force_download set to True, downloading to /root/.cache/torch/transformers/tmpjarc50dv


INFO:transformers.file_utils:storing https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt in cache at /root/.cache/torch/transformers/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
INFO:transformers.file_utils:creating metadata file for /root/.cache/torch/transformers/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
INFO:filelock:Lock 140709407808368 released on /root/.cache/torch/transformers/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084.lock
INFO:transformers.tokenization_utils:loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /root/.cache/torch/transformers/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f7

In [5]:
# Load pre-trained model (weights)
model = BertModel.from_pretrained('bert-base-uncased')

# Set the model in evaluation mode to deactivate the DropOut modules
# This is IMPORTANT to have reproducible results during evaluation!
model.eval()

# If you have a GPU, put everything on cuda
tokens_tensor = tokens_tensor.to('cuda')
segments_tensors = segments_tensors.to('cuda')
model.to('cuda')

# Predict hidden states features for each layer
with torch.no_grad():
    # See the models docstrings for the detail of the inputs
    outputs = model(tokens_tensor, token_type_ids=segments_tensors)
    # Transformers models always output tuples.
    # See the models docstrings for the detail of all the outputs
    # In our case, the first element is the hidden state of the last layer of the Bert model
    encoded_layers = outputs[0]
# We have encoded our input sequence in a FloatTensor of shape (batch size, sequence length, model hidden dimension)
assert tuple(encoded_layers.shape) == (1, len(indexed_tokens), model.config.hidden_size)

INFO:filelock:Lock 140710645151448 acquired on /root/.cache/torch/transformers/4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.7156163d5fdc189c3016baca0775ffce230789d7fa2a42ef516483e4ca884517.lock
INFO:transformers.file_utils:https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json not found in cache or force_download set to True, downloading to /root/.cache/torch/transformers/tmpyqdc5dp_


INFO:transformers.file_utils:storing https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json in cache at /root/.cache/torch/transformers/4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.7156163d5fdc189c3016baca0775ffce230789d7fa2a42ef516483e4ca884517
INFO:transformers.file_utils:creating metadata file for /root/.cache/torch/transformers/4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.7156163d5fdc189c3016baca0775ffce230789d7fa2a42ef516483e4ca884517
INFO:filelock:Lock 140710645151448 released on /root/.cache/torch/transformers/4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.7156163d5fdc189c3016baca0775ffce230789d7fa2a42ef516483e4ca884517.lock
INFO:transformers.configuration_utils:loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json from cache at /root/.cache/torch/transformers/4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.7156163d5fdc189c3

INFO:filelock:Lock 140709388298504 acquired on /root/.cache/torch/transformers/f2ee78bdd635b758cc0a12352586868bef80e47401abe4c4fcc3832421e7338b.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157.lock
INFO:transformers.file_utils:https://cdn.huggingface.co/bert-base-uncased-pytorch_model.bin not found in cache or force_download set to True, downloading to /root/.cache/torch/transformers/tmpcwua21fx


INFO:transformers.file_utils:storing https://cdn.huggingface.co/bert-base-uncased-pytorch_model.bin in cache at /root/.cache/torch/transformers/f2ee78bdd635b758cc0a12352586868bef80e47401abe4c4fcc3832421e7338b.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157
INFO:transformers.file_utils:creating metadata file for /root/.cache/torch/transformers/f2ee78bdd635b758cc0a12352586868bef80e47401abe4c4fcc3832421e7338b.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157
INFO:filelock:Lock 140709388298504 released on /root/.cache/torch/transformers/f2ee78bdd635b758cc0a12352586868bef80e47401abe4c4fcc3832421e7338b.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157.lock
INFO:transformers.modeling_utils:loading weights file https://cdn.huggingface.co/bert-base-uncased-pytorch_model.bin from cache at /root/.cache/torch/transformers/f2ee78bdd635b758cc0a12352586868bef80e47401abe4c4fcc3832421e7338b.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157
